In [24]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/rjmanoj/credit-card-customer-churn-prediction/Churn_Modelling.csv


In [25]:
import kagglehub


# Download latest version
path = kagglehub.dataset_download("rjmanoj/credit-card-customer-churn-prediction")

print("Path to dataset files:", path)

Path to dataset files: /kaggle/input/datasets/rjmanoj/credit-card-customer-churn-prediction


In [26]:
df = pd.read_csv("/kaggle/input/datasets/rjmanoj/credit-card-customer-churn-prediction/Churn_Modelling.csv")
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1


In [27]:
df.shape

(10000, 14)

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [29]:
df.duplicated().sum()

np.int64(0)

In [30]:
df['Exited'].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [31]:
df['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [32]:
df['Gender'].value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

In [33]:
df.drop(columns=['RowNumber','CustomerId','Surname'],inplace=True)

In [20]:
df.shape

(10000, 11)

In [34]:
df = pd.get_dummies(df, columns=['Geography','Gender'], drop_first=True, dtype=int)

In [35]:
df

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,0,0,0
1,608,41,1,83807.86,1,0,1,112542.58,0,0,1,0
2,502,42,8,159660.80,3,1,0,113931.57,1,0,0,0
3,699,39,1,0.00,2,0,0,93826.63,0,0,0,0
4,850,43,2,125510.82,1,1,1,79084.10,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,0,0,0,1
9996,516,35,10,57369.61,1,1,1,101699.77,0,0,0,1
9997,709,36,7,0.00,1,0,1,42085.58,1,0,0,0
9998,772,42,3,75075.31,2,1,0,92888.52,1,1,0,1


In [36]:
# let us scale the values first before entering it into neural network

In [42]:
X = df.drop(columns=['Exited'])
y = df['Exited']
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)


In [44]:
X_train.shape

(8000, 11)

In [45]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)

In [46]:
X_train_scaled

array([[-0.23082038, -0.94449979, -0.70174202, ...,  1.71490137,
        -0.57273139,  0.91509065],
       [-0.25150912, -0.94449979, -0.35520275, ..., -0.58312392,
        -0.57273139, -1.09278791],
       [-0.3963303 ,  0.77498705,  0.33787579, ...,  1.71490137,
        -0.57273139, -1.09278791],
       ...,
       [ 0.22433188,  0.58393295,  1.3774936 , ..., -0.58312392,
        -0.57273139, -1.09278791],
       [ 0.13123255,  0.01077067,  1.03095433, ..., -0.58312392,
        -0.57273139, -1.09278791],
       [ 1.1656695 ,  0.29735181,  0.33787579, ...,  1.71490137,
        -0.57273139,  0.91509065]])

In [48]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [66]:
#using sequential model
model = Sequential()
model.add(Dense(11,activation='relu',input_dim = 11)) #in our hidden layer we are putting 3 perceptrons which would be getting 11 inputs
model.add(Dense(11,activation='relu'))
model.add(Dense(1,activation='sigmoid')) # one output

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [67]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_8 (Dense)                 │ (None, 11)             │           132 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 11)             │           132 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 1)              │            12 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 276 (1.08 KB)

 Trainable params: 276 (1.08 KB)

 Non-trainable params: 0 (0.00 B)

In [68]:
model.compile(
    loss='binary_crossentropy',
    optimizer='Adam',
    metrics=[
        'accuracy',
        tensorflow.keras.metrics.Precision(),
        tensorflow.keras.metrics.Recall(),
        tensorflow.keras.metrics.AUC()
    ],
    
)

In [69]:
model.fit(X_train_scaled,y_train,epochs=100,validation_split=0.2)

Epoch 1/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7806 - auc: 0.5340 - loss: 0.5522 - precision: 0.3072 - recall: 0.0178 - val_accuracy: 0.7975 - val_auc: 0.6858 - val_loss: 0.4709 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 2/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8011 - auc: 0.7119 - loss: 0.4566 - precision: 0.2604 - recall: 0.0034 - val_accuracy: 0.8000 - val_auc: 0.7329 - val_loss: 0.4477 - val_precision: 0.5667 - val_recall: 0.0525
Epoch 3/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8023 - auc: 0.7497 - loss: 0.4438 - precision: 0.6937 - recall: 0.0698 - val_accuracy: 0.8125 - val_auc: 0.7524 - val_loss: 0.4361 - val_precision: 0.7143 - val_recall: 0.1235
Epoch 4/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8191 - auc: 0.7674 - loss: 0.4225 - precision: 0.6989 - recall: 0.1592 - val_accuracy: 0.8119 - val_auc: 0.7613 - val_loss: 0.4296 - val_precision: 0.6494 - val_recall: 0.1543
Epoch 5/100
200/200 

In [70]:
#now let us see the values of teh calculated weights and biases
model.layers[0].get_weights()

[array([[-0.11804246,  0.14254482,  0.01292267, -0.07972973, -0.04320924,
          0.5914655 ,  0.07438048, -0.04581686,  0.11904182,  0.25913298,
          0.0330843 ],
        [-0.5743897 ,  0.36105144, -0.60033476, -0.795359  ,  0.77100235,
         -0.05408982, -0.20981488, -0.91740125, -0.17059849, -0.89351946,
         -0.85672903],
        [ 0.25849473, -0.16284256, -0.03433274,  0.00830935,  0.25720167,
         -0.58257705, -0.16357361, -0.07557072, -0.05233163, -0.17399295,
          0.03645156],
        [ 0.14981335, -0.33175373, -1.0204351 ,  0.1226    ,  0.24922313,
         -0.14997144,  0.14032169,  0.71652883,  0.63027495,  0.6717265 ,
         -0.12698378],
        [ 0.7864899 ,  0.30146277,  0.15364768,  0.25570646,  0.33736604,
         -0.02846672,  0.97411865, -0.29003295,  1.1196735 ,  0.17946805,
          0.40470552],
        [-0.3817785 , -0.42821357, -0.0018794 ,  0.1311813 ,  0.21515712,
         -0.09668593, -0.25671935, -0.03850786,  0.15730774, -0.2169220

In [71]:
model.layers[1].get_weights()

[array([[ 5.4915369e-01,  3.5490561e-02,  2.8043771e-01,  9.3211621e-02,
         -5.1913434e-01,  2.5070590e-01,  2.7519232e-02,  3.1653982e-01,
          3.2083753e-01,  3.8937488e-01,  3.4229505e-01],
        [ 4.3090528e-01, -9.3836153e-01,  8.0904573e-02,  1.7787859e-01,
          2.6284227e-01,  1.5680639e-01, -1.1653805e-01,  5.4988855e-01,
         -4.2453176e-01,  2.5273117e-01,  6.9024271e-01],
        [-5.5627519e-01,  6.3104111e-01,  2.0179245e-01, -5.2924752e-01,
         -3.2438669e-01, -6.7553496e-01, -1.5048946e+00,  1.9931884e-02,
          1.3300987e-01,  4.3340924e-01,  1.0337274e+00],
        [-1.8011717e-01, -2.1280265e-01, -1.8531178e-01,  8.8220380e-02,
         -7.8396492e-02, -3.1984028e-01,  2.2373749e-01,  9.0618914e-01,
          3.6942157e-01, -6.3247251e-04, -2.2930957e-01],
        [-6.1149931e-01, -6.5724391e-01, -3.1765658e-01, -4.5325267e-01,
         -1.0175400e-01, -6.6595182e-02, -1.7007960e+00, -4.3305984e-01,
          7.1646619e-01,  7.1216804e-0

In [72]:
model.layers[1].get_weights()

[array([[ 5.4915369e-01,  3.5490561e-02,  2.8043771e-01,  9.3211621e-02,
         -5.1913434e-01,  2.5070590e-01,  2.7519232e-02,  3.1653982e-01,
          3.2083753e-01,  3.8937488e-01,  3.4229505e-01],
        [ 4.3090528e-01, -9.3836153e-01,  8.0904573e-02,  1.7787859e-01,
          2.6284227e-01,  1.5680639e-01, -1.1653805e-01,  5.4988855e-01,
         -4.2453176e-01,  2.5273117e-01,  6.9024271e-01],
        [-5.5627519e-01,  6.3104111e-01,  2.0179245e-01, -5.2924752e-01,
         -3.2438669e-01, -6.7553496e-01, -1.5048946e+00,  1.9931884e-02,
          1.3300987e-01,  4.3340924e-01,  1.0337274e+00],
        [-1.8011717e-01, -2.1280265e-01, -1.8531178e-01,  8.8220380e-02,
         -7.8396492e-02, -3.1984028e-01,  2.2373749e-01,  9.0618914e-01,
          3.6942157e-01, -6.3247251e-04, -2.2930957e-01],
        [-6.1149931e-01, -6.5724391e-01, -3.1765658e-01, -4.5325267e-01,
         -1.0175400e-01, -6.6595182e-02, -1.7007960e+00, -4.3305984e-01,
          7.1646619e-01,  7.1216804e-0

In [74]:
X_test_scaled = scaler.transform(X_test)

In [75]:

model.predict(X_test_scaled)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step


array([[0.02200434],
       [0.06142683],
       [0.14823647],
       ...,
       [0.0025787 ],
       [0.01850398],
       [0.261202  ]], dtype=float32)

In [76]:
# now these are teh sigmoid probabilities , we now have to decide a threshold , above which there will be one and below which there will be zero
y_log = model.predict(X_test_scaled)


63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step


In [78]:
y_pred = np.where(y_log>0.5,1,0)
y_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [80]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)


0.865